apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-mainroad-uof
spec:
  displayName: Mainroad (UOF)
  author:
    name: 一个达不刘
    website: https://www.halo.run
  description: A Halo Theme for Hugo Mainroad
  logo: /themes/theme-mainroad/assets/images/favicon.png
  website: https://liuchang.halo.run
  repo: https://github.com/Universityu-Of-Fool/halo-theme-mainroad-uof.git
  settingName: "theme-mainroad-setting"
  configMapName: "theme-mainroad-configMap"
  version: 1.2.2
  require: ">=2.0.0"
